'''
To address memory constraints in Slicer, first slice the block into 128×3 blocks to generate labels, then aggregate these into a 512×512 2D label.
Import the label (.json) generated by Slicer (128×128x128)
Process into corresponding .txt label files for each block
and aggregate into a 512×512 2D label (as a .txt file; further processing via txt_conver.py is required to convert to .xml/.json files)

Output the 2D/3D annotation results for the (128×128x128) blocks in .txt format, placed in output_2d_path/output_3d_path/output_yolo_path
Output the consolidated 512×3 2D .txt results, placed in output_block_path
'''

import os
import glob
import json
import sys
import numpy as np
import pandas as pd
import json
import math

base_dir = "./test/"
output_path = "./test/"
name_dict = {1:"diffuse", 2:"core", 3:"CAA", 4:"cotton"}


def load_json(image_size, block_dir):
    df_2d_all = pd.DataFrame()
    df_3d_all = pd.DataFrame()
    file_names = next(os.walk(block_dir))[-1]
    file_names.sort(key=lambda x:(x.split('.')[0]))
    i = 0
    for file_name in file_names:
        file_suffix = os.path.splitext(file_name)[-1]
        if file_suffix != ".json":
            continue
        cls = name_dict[int(file_name[0])]
        json_dir = os.path.join(block_dir, file_name)
        with open(json_dir, "r", encoding='utf-8') as f:
            bbox = json.load(f)
            center = bbox['markups'][0]['center']
            size = bbox['markups'][0]['size']
        x_c,y_c,z_c = center
        w,h,l = size
        x_r = w/2
        y_r = h/2
        z_r = l/2
        if (x_c<x_r)or((image_size-x_c)<x_r):
            if x_c<x_r:
                x_r = (x_r + x_c)/2
                x_c = x_r
            else:
                x_r = (image_size - x_c + x_r)/2
                x_c = image_size - x_r
            w = x_r*2
        if (y_c<y_r)or((image_size-y_c)<y_r):
            if y_c<y_r:
                y_r = (y_r + y_c)/2
                y_c = y_r
            else:
                y_r = (image_size - y_c + y_r)/2
                y_c = image_size - y_r
            h = y_r*2
        if (z_c<z_r)or((image_size-z_c)<z_r):
            if z_c<z_r:
                z_r = (z_r + z_c)/2
                z_c = z_r
            else:
                z_r = (image_size - z_c + z_r)/2
                z_c = image_size - z_r
            l =z_r*2
        x_min = x_c - x_r
        y_min = y_c - y_r
        z_min = z_c - z_r
        x_max = x_c + x_r
        y_max = y_c + y_r
        z_max = z_c + z_r
        df_3d_all[i] = pd.Series({"x_min": int(x_min),
                                  "y_min": int(y_min),
                                  "z_min": int(z_min),
                                  "x_max": math.ceil(x_max),
                                  "y_max": math.ceil(y_max),
                                  "z_max": math.ceil(z_max),
                                  "x_center": int(x_c),
                                  "y_center": int(y_c),
                                  "z_center": int(z_c),
                                  "x_r": math.ceil(x_r),
                                  "y_r": math.ceil(y_r),
                                  "z_r": math.ceil(z_r),
                                  "class": cls })
        i = i+1
        df_2d_apart = pd.DataFrame()
        for j in range(math.ceil(l) + 1):
            df_2d_apart[j] = pd.Series({"x_min": int(x_min),
                                        "y_min": int(y_min),
                                        "x_max": math.ceil(x_max),
                                        "y_max": math.ceil(y_max),
                                        "width": math.ceil(w),
                                        "height": math.ceil(h),
                                        "z": int(z_min) + j,
                                        "class": cls })
        df_2d_all = df_2d_all.append(df_2d_apart.T) 
    df_3d_all = (df_3d_all.T).reset_index(drop=True)
    df_2d_all = df_2d_all.reset_index(drop=True)
    return df_3d_all, df_2d_all

def output_2d(df_2d_all, image_size, output_2d_path):
    for i in range(image_size):
        i = i+1
        df_2d = df_2d_all.loc[df_2d_all['z'] == i]
        df_2d_all = df_2d_all.drop(index=(df_2d.index.tolist()))
        df_2d = df_2d.reset_index(drop=True)
        #df_2d.to_excel(output_2d_path + str(i) + '.xls')
        df_2d.to_csv(output_2d_path + str(i) + '.txt', sep=' ',index=False, header=False)
        if (len(df_2d_all) == 0):
            break
    for j in range(image_size-i):
        open(output_2d_path + str(i+j+1) + '.txt', "w")

def block_label_process(output_block_path):
    block_names = next(os.walk(base_dir))[1]
    block_names.sort(key=lambda x:(x.split('.')[0]))
    block_3d_all = pd.DataFrame()
    block_2d_all = pd.DataFrame()
    for block_name in block_names:
        block_dir = os.path.join(base_dir, block_name)
        df_3d_all, df_2d_all = load_json(128, block_dir)
        output_2d_path = os.path.join(block_dir, block_name+"_2d/")
        if (block_name+"_2d") not in os.listdir(block_dir):
            os.mkdir(output_2d_path)
        output_2d(df_2d_all, 128, output_2d_path)
        output_3d_path = os.path.join(block_dir, block_name+".txt")
        output_yolo_path = os.path.join(block_dir, block_name+"_yolo.txt")
        df_3d = df_3d_all.loc[:, ['x_min', 'y_min', 'z_min', 'x_max','y_max', 'z_max', 'class']]
        df_yolo = df_3d_all.loc[:, ['x_center','y_center', 'z_center', 'x_r', 'y_r', 'z_r', 'class']]
        df_3d.to_csv(output_3d_path, sep=' ',index=False, header=False)
        df_yolo.to_csv(output_yolo_path, sep=' ',index=False, header=False)
        
        if int(block_name) != 1:
            i = int(block_name/16)
            j = int((block_name - i*16)/4)
            k = int(block_name - i*16 - j*4)
            for m in len(df_3d_all):
                df_3d_all.iloc[m]['z_min'] = df_3d_all.iloc[m]['z_min'] + i*128
                df_3d_all.iloc[m]['z_max'] = df_3d_all.iloc[m]['z_max'] + i*128
                df_3d_all.iloc[m]['z_center'] = df_3d_all.iloc[m]['z_center'] + i*128
                df_3d_all.iloc[m]['y_min'] = df_3d_all.iloc[m]['y_min'] + j*128
                df_3d_all.iloc[m]['y_max'] = df_3d_all.iloc[m]['y_max'] + j*128
                df_3d_all.iloc[m]['y_center'] = df_3d_all.iloc[m]['y_center'] + j*128
                df_3d_all.iloc[m]['x_min'] = df_3d_all.iloc[m]['x_min'] + (k-1)*128
                df_3d_all.iloc[m]['x_max'] = df_3d_all.iloc[m]['x_max'] + (k-1)*128
                df_3d_all.iloc[m]['x_center'] = df_3d_all.iloc[m]['x_center'] + (k-1)*128
        block_3d_all = block_3d_all.append(df_3d_all)
    block_3d_all = block_3d_all.reset_index(drop=True)
    
    for n in len(block_3d_all):
        df_2d_apart = pd.DataFrame()
        l = 2 * df_3d_all.iloc[n]['z_r']
        for j in range(l + 1):
            df_2d_apart[j] = pd.Series({"x_min": df_3d_all.iloc[n]['x_min'],
                                        "y_min": df_3d_all.iloc[n]['y_min'],
                                        "x_max": df_3d_all.iloc[n]['x_max'],
                                        "y_max": df_3d_all.iloc[n]['y_max'],
                                        "width": 2 * df_3d_all.iloc[n]['x_r'],
                                        "height": 2 * df_3d_all.iloc[n]['y_r'],
                                        "z": df_3d_all.iloc[n]['z_min'] + j,
                                        "class": df_3d_all.iloc[n]['class'] })
        block_2d_all = block_2d_all.append(df_2d_apart.T) 
    block_2d_all = block_2d_all.reset_index(drop=True)
    output_2d(block_2d_all, 512, output_block_path)


if __name__ == "__main__": 
    output_block_path = output_path + '2d/'
    if '2d' not in os.listdir(output_path):
        os.mkdir(output_block_path)
    block_label_process(output_block_path)
